//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCLOTHINGWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMAIL()
        {
            this.EMAIL_LIST = new HashSet<EMAIL_LIST>();
        }
    
        public int ID { get; set; }
        public string Date { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<int> SentBy { get; set; }
    
        public virtual ADMINS ADMINS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAIL_LIST> EMAIL_LIST { get; set; }
    }
}
