//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCLOTHINGWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_LIST
    {
        public int ID { get; set; }
        public Nullable<int> EmailID { get; set; }
        public Nullable<int> Recepient { get; set; }
    
        public virtual EMAIL EMAIL { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
