//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCLOTHINGWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iCLOTHINGEntities : DbContext
    {
        public iCLOTHINGEntities()
            : base("name=iCLOTHINGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINS> ADMINS { get; set; }
        public virtual DbSet<BILLINGINFO> BILLINGINFO { get; set; }
        public virtual DbSet<BRAND> BRAND { get; set; }
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<CATEGORY_ITEMS> CATEGORY_ITEMS { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENT { get; set; }
        public virtual DbSet<EMAIL> EMAIL { get; set; }
        public virtual DbSet<EMAIL_LIST> EMAIL_LIST { get; set; }
        public virtual DbSet<FEEDBACK> FEEDBACK { get; set; }
        public virtual DbSet<ITEM> ITEM { get; set; }
        public virtual DbSet<ORDERS> ORDERS { get; set; }
        public virtual DbSet<SHOPPINGCART> SHOPPINGCART { get; set; }
        public virtual DbSet<SPECIAL_QUERY> SPECIAL_QUERY { get; set; }
        public virtual DbSet<SUBCATEGORY> SUBCATEGORY { get; set; }
        public virtual DbSet<SUBCATEGORY_ITEMS> SUBCATEGORY_ITEMS { get; set; }
        public virtual DbSet<USERPASSWORD> USERPASSWORD { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
